const defaultTheme = {
  color: {
    primary: 'gainsboro',
    secondary: 'lightgray',
    tertiary: 'silver',
    highlight: 'orange',
    white: 'white',
    black: 'darkslategray'
  },
  colorTintIncrement: 10,
  colorShadeIncrement: 10,
  spacing: {
    unit: 'px',
    0: 0,
    1: 1,
    2: 2,
    3: 4,
    4: 8,
    5: 12,
    6: 16,
    7: 20,
    8: 24,
    9: 28,
    10: 32,
  },
  fontSize: {
    unit: 'px',
    0: 0,
    1: 8,
    2: 10,
    3: 12,
    4: 14,
    5: 16,
    6: 20,
    7: 24,
  },
  opacity: {
    1: 1.0,
    2: 0.75,
    3: 0.5,
    4: 0.25,
    5: 0.0,
  },
  InputTextColor: 'primary',
  InputTextColorFocused: 'highlight',
  InputTextBackgroundColor: 'white',
  InputTextBackgroundColorFocused: 'white',
  InputTextBorderRadius: 3,
  InputTextBorderColor: 'primary',
  InputTextBorderColorFocused: 'highlight',
  InputTextBorderWidth: 2,
  InputTextPadding: [4, 6],
}

const darkTheme = {
  color: {
    primary: 'gainsboro',
    secondary: 'lightgray',
    tertiary: 'silver',
    highlight: 'purple',
    white: 'white',
    black: 'darkslategray'
  },
  spacing: {
    unit: 'px',
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 16,
    '5': 20,
    '6': 24,
    '7': 28,
    '8': 32,
  },
  fontSize: {
    unit: 'px',
    0: 0,
    1: 8,
    2: 10,
    3: 12,
    4: 14,
    5: 16,
    6: 20,
    7: 24,
  },
  opacity: {
    1: 1.0,
    2: 0.75,
    3: 0.5,
    4: 0.25,
    5: 0.0,
  },
  InputTextColor: 'primary',
  InputTextColorFocused: 'highlight',
  InputTextBackgroundColor: 'white',
  InputTextBackgroundColorFocused: 'white',
  InputTextBorderRadius: 2,
  InputTextBorderColor: 'primary',
  InputTextBorderColorFocused: 'highlight',
  InputTextBorderWidth: 2,
  InputTextPadding: [4, 5],
}

export { defaultTheme, darkTheme }
